apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb-binlog
  namespace: storage-external
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Block
