---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: weblog
  namespace: storage-review
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
