---
- name: Remove VM network
  hosts: utility
  remote_user: lab
  gather_facts: False
  module_defaults:
    group/k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"
  tasks:
    - name: Remove vm-private-net network attachment
      k8s:
        state: absent
        api_version: k8s.cni.cncf.io/v1
        kind: NetworkAttachmentDefinition
        namespace: default
        name: vm-private-net

- import_playbook: ../roles/verify-worker-nodes.yml

...
