apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br0-ens4-policy
spec:
  nodeSelector:
    orgnet: "true"
  desiredState:
    interfaces:
      - name: br0
        description: Linux bridge with ens4 as a port
        type: linux-bridge
        state: up
        ipv4:
          dhcp: true
          enabled: true
        bridge:
          options:
            stp:
              enabled: false
          port:
            - name: ens4
