apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
    name.os.template.kubevirt.io/rhel9.3: Red Hat Enterprise Linux 9.0 or higher
    description: Using a disk snapshot to create a VM
  labels:
    app: vm2
    vm.kubevirt.io/template: rhel9-server-tiny
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.26.0
    os.template.kubevirt.io/rhel9.3: 'true'
    flavor.template.kubevirt.io/tiny: 'true'
    workload.template.kubevirt.io/server: 'true'
    vm.kubevirt.io/template.namespace: openshift
  name: vm2
  namespace: advanced-snapshot
spec:
  running: true
  template:
    metadata:
      annotations:
        vm.kubevirt.io/flavor: tiny
        vm.kubevirt.io/os: rhel9
        vm.kubevirt.io/workload: server
      labels:
        kubevirt.io/domain: vm2
        kubevirt.io/size: tiny
        vm.kubevirt.io/name: vm2
        os.template.kubevirt.io/rhel9.3: 'true'
        flavor.template.kubevirt.io/tiny: 'true'
        workload.template.kubevirt.io/server: 'true'
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
            - bootOrder: 1
              disk:
                bus: virtio
              name: containerdisk
          interfaces:
            - masquerade: {}
              model: virtio
              name: default
          networkInterfaceMultiqueue: true
          rng: {}
        machine:
          type: pc-q35-rhel9.2.0
        resources:
          requests:
            memory: 1.5Gi
      evictionStrategy: LiveMigrate
      hostname: vm2
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - name: containerdisk
          persistentVolumeClaim:
            claimName: <CHANGE_ME>
