apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: br0-network
  namespace: multihomed-review
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br0
spec:
  config: '{
    "cniVersion": "0.3.1",
    "name": "br1-network",
    "plugins": [
      {
        "type": "cnv-bridge",
        "bridge": "br0"
      },
      {
        "type": "cnv-tuning"
      }
    ]
  }'
