---
- name: Log in as developer
  command: >
    oc login -u {{ users[0] }} -p {{ passwd[0] }}

- name: Log in as remaining users
  command: >
    oc login -u {{ item }} -p {{ passwd[1] }}
  with_items:
    - dbadmin1
    - dbadmin2
    - admin
  ignore_errors: True
