---
- name: Remove VNC console access to group
  k8s:
    state: absent
    inline:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: allow-vnc-console-to-group
      subjects:
        - kind: Group
          apiGroup: rbac.authorization.k8s.io
          name: database-admins
      roleRef:
        kind: ClusterRole
        apiGroup: rbac.authorization.k8s.io
        name: allow-vnc-console-access

- name: Remove allow-clone-to-user role binding
  k8s:
    state: absent
    inline:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: allow-clone-to-user
        namespace: "{{ item }}"
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: "{{ vm_namespace[1] }}"
      - kind: ServiceAccount
        name: default
        namespace: "{{ vm_namespace[2] }}"
      roleRef:
        kind: ClusterRole
        name: datavolume-cloner
        apiGroup: rbac.authorization.k8s.io
  with_items:
    - "{{ vm_namespace[0] }}"

- name: Remove datavolume-cloner cluster role
  k8s:
    state: absent
    inline:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: datavolume-cloner
      rules:
      - apiGroups: ["cdi.kubevirt.io"]
        resources: ["datavolumes/source"]
        verbs: ["*"]
