---
- name: Create the vm1 virtual machine
  hosts: utility
  remote_user: lab
  gather_facts: false
  module_defaults:
    group/k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"
  vars:
    vm_namespace: advanced-migrate
    vm_name: vm1
    vm_app: webapp
    utility_url: http://utility.lab.example.com:8080/openshift4/images/
    vm_qcow2: rhel9-helloworld.qcow2
    vm_size: 15Gi
    vm_sc_name: ocs-external-storagecluster-ceph-rbd-virtualization
    vm_sc_mode: Block
    tmp_sc_name: nfs-storage
    tmp_sc_mode: Filesystem

  tasks:
    - name: Ensure that the project exists
      k8s:
        state: present
        inline:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ vm_namespace }}"

    - name: Confirm that the admin user is logged in on Utility
      command: >
        oc login -u admin -p redhatocp "{{ ocp_cluster['host'] }}"

    - name: Change NFS access mode to RWO
      command: >
        oc patch -n openshift-cnv storageprofiles.cdi.kubevirt.io nfs-storage --type='merge' --patch='{"spec":{"claimPropertySets": [{"accessModes": ["ReadWriteOnce"],"volumeMode": "FileSystem"}]}}'
      ignore_errors: yes

    - name: Ensure that the virtual machine and the data volume exist
      k8s:
        state: present
        namespace: "{{ vm_namespace }}"
        inline:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name }}"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_app }}"
              kubevirt.io/vm: "{{ vm_name }}"
              flavor.template.kubevirt.io/small: 'true'
              os.template.kubevirt.io/rhel9.3: 'true'
              vm.kubevirt.io/template: rhel9-server-small
              vm.kubevirt.io/template.namespace: openshift
              vm.kubevirt.io/template.revision: '1'
              vm.kubevirt.io/template.version: v0.26.0
              workload.template.kubevirt.io/server: 'true'
          spec:
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: "{{ vm_name }}"
                spec:
                  pvc:
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: "{{ vm_size }}"
                    storageClassName: "{{ vm_sc_name }}"
                    volumeMode: "{{ vm_sc_mode }}"
                  source:
                    http:
                      url: "{{ utility_url}}{{ vm_qcow2 }}"
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: tempdata
                spec:
                  pvc:
                    accessModes:
                      - ReadWriteOnce
                    resources:
                      requests:
                        storage: 2Gi
                    storageClassName: "{{ tmp_sc_name }}"
                    volumeMode: "{{ tmp_sc_mode }}"
                  source:
                    blank: {}
            runStrategy: RerunOnFailure
            template:
              metadata:
                labels:
                  flavor.template.kubevirt.io/small: 'true'
                  kubevirt.io/domain: "{{ vm_name }}"
                  kubevirt.io/size: small
                  os.template.kubevirt.io/rhel9.3: 'true'
                  workload.template.kubevirt.io/server: 'true'
              spec:
                domain:
                  cpu:
                    cores: 1
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - bootOrder: 1
                        disk:
                          bus: virtio
                        name: "{{ vm_name }}"
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                      - disk:
                          bus: virtio
                        name: tempdata
                    interfaces:
                      - name: default
                        masquerade: {}
                    networkInterfaceMultiqueue: true
                    rng: {}
                  machine:
                    type: pc-q35-rhel9.2.0
                  resources:
                    requests:
                      memory: 2Gi
                hostname: "{{ vm_name }}"
                evictionStrategy: null
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                volumes:
                  - dataVolume:
                      name: "{{ vm_name }}"
                    name: "{{ vm_name }}"
                  - dataVolume:
                      name: tempdata
                    name: tempdata
                  - cloudInitNoCloud:
                      userData: |-
                        #cloud-config
                        user: developer
                        password: developer
                        chpasswd: { expire: False }
                    name: cloudinitdisk
        wait: yes
        wait_condition:
          type: Ready
          status: "True"
        wait_sleep: 60
        wait_timeout: 1800

...
