---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: CHANGE_ME
  namespace: CHANGE_ME
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
