---
  - name: Remove allow-clone-to-user role binding
    k8s:
      state: absent
      inline:
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: allow-clone-to-user
          namespace: "{{ vm_namespace[0] }}"
        subjects:
        - kind: ServiceAccount
          name: default
          namespace: "{{ vm_namespace[0] }}"
        - kind: ServiceAccount
          name: default
          namespace: "{{ vm_namespace[1] }}"
        - kind: ServiceAccount
          name: default
          namespace: "{{ vm_namespace[2] }}"
        roleRef:
          kind: ClusterRole
          name: datavolume-cloner
          apiGroup: rbac.authorization.k8s.io
