---
- name: Create Project, VM, and datavolume
  hosts: utility
  remote_user: lab
  gather_facts: False
  module_defaults:
    group/k8s:
      host: "{{ ocp_cluster['host'] }}"
      kubeconfig: "{{ ocp_cluster['kubeconfig'] }}"
      validate_certs: "{{ ocp_cluster['validate_certs'] }}"
  vars:
    vm_namespace: ha-loadbalance
    vm_name: [server1, server2]
    vm_app: helloworld
    utility_url: http://utility.lab.example.com:8080/openshift4/images/
    vm_qcow2: helloworld.qcow2
    vm_size: 10Gi
    vm_sc_name: ocs-external-storagecluster-ceph-rbd-virtualization
    vm_sc_mode: Block

  tasks:
    - name: Create {{ vm_namespace }} project
      k8s:
        state: present
        inline:
          apiVersion: project.openshift.io/v1
          kind: Project
          metadata:
            name: "{{ vm_namespace }}"

    - name: Create {{ vm_name[0] }} vm and dv
      k8s:
        state: present
        namespace: "{{ vm_namespace }}"
        inline:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name[0] }}"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_app }}"
              kubevirt.io/vm: "{{ vm_name[0] }}"
              flavor.template.kubevirt.io/small: 'true'
              os.template.kubevirt.io/rhel8.4: 'true'
              vm.kubevirt.io/template: rhel8-server-small
              vm.kubevirt.io/template.namespace: openshift
              vm.kubevirt.io/template.revision: '1'
              vm.kubevirt.io/template.version: v0.26.0
              workload.template.kubevirt.io/server: 'true'
          spec:
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: "{{ vm_name[0] }}"
                spec:
                  pvc:
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: "{{ vm_size }}"
                    storageClassName: "{{ vm_sc_name }}"
                    volumeMode: "{{ vm_sc_mode }}"
                  source:
                    http:
                      url: "{{ utility_url}}{{ vm_qcow2 }}"
            runStrategy: RerunOnFailure
            template:
              metadata:
                labels:
                  app: "{{ vm_app }}"
                  flavor.template.kubevirt.io/small: 'true'
                  kubevirt.io/domain: "{{ vm_name[0] }}"
                  kubevirt.io/size: small
                  os.template.kubevirt.io/rhel8.4: 'true'
                  workload.template.kubevirt.io/server: 'true'
              spec:
                domain:
                  cpu:
                    cores: 1
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - bootOrder: 1
                        disk:
                          bus: virtio
                        name: "{{ vm_name[0] }}"
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                    interfaces:
                      - name: default
                        masquerade: {}
                    networkInterfaceMultiqueue: true
                    rng: {}
                  machine:
                    type: pc-q35-rhel8.4.0
                  resources:
                    requests:
                      memory: 2Gi
                evictionStrategy: LiveMigrate
                hostname: "{{ vm_name[0] }}"
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                volumes:
                  - dataVolume:
                      name: "{{ vm_name[0] }}"
                    name: "{{ vm_name[0] }}"
                  - cloudInitNoCloud:
                      userData: |-
                        #cloud-config
                        user: developer
                        password: developer
                        chpasswd: { expire: False }
                        runcmd:
                          - sudo sed -i "s/! Welcome to Red Hat Training/, from $HOSTNAME/g" /var/www/html/index.html
                          - sudo restorecon -Rv /var/www/html/
                    name: cloudinitdisk
        wait: yes
        wait_condition:
          type: Ready
          status: "True"
        wait_sleep: 60
        wait_timeout: 1800

    - name: Create {{ vm_name[1] }} vm and dv
      k8s:
        state: present
        namespace: "{{ vm_namespace }}"
        inline:
          apiVersion: kubevirt.io/v1
          kind: VirtualMachine
          metadata:
            name: "{{ vm_name[1] }}"
            namespace: "{{ vm_namespace }}"
            labels:
              app: "{{ vm_app }}"
              kubevirt.io/vm: "{{ vm_name[1] }}"
              flavor.template.kubevirt.io/small: 'true'
              os.template.kubevirt.io/rhel8.4: 'true'
              vm.kubevirt.io/template: rhel8-server-small
              vm.kubevirt.io/template.namespace: openshift
              vm.kubevirt.io/template.revision: '1'
              vm.kubevirt.io/template.version: v0.26.0
              workload.template.kubevirt.io/server: 'true'
          spec:
            dataVolumeTemplates:
              - apiVersion: cdi.kubevirt.io/v1beta1
                kind: DataVolume
                metadata:
                  name: "{{ vm_name[1] }}"
                spec:
                  pvc:
                    accessModes:
                      - ReadWriteMany
                    resources:
                      requests:
                        storage: "{{ vm_size }}"
                    storageClassName: "{{ vm_sc_name }}"
                    volumeMode: "{{ vm_sc_mode }}"
                  source:
                    http:
                      url: "{{ utility_url}}{{ vm_qcow2 }}"
            runStrategy: RerunOnFailure
            template:
              metadata:
                labels:
                  app: "{{ vm_app }}"
                  flavor.template.kubevirt.io/small: 'true'
                  kubevirt.io/domain: "{{ vm_name[1] }}"
                  kubevirt.io/size: small
                  os.template.kubevirt.io/rhel8.4: 'true'
                  workload.template.kubevirt.io/server: 'true'
              spec:
                domain:
                  cpu:
                    cores: 1
                    sockets: 1
                    threads: 1
                  devices:
                    disks:
                      - bootOrder: 1
                        disk:
                          bus: virtio
                        name: "{{ vm_name[1] }}"
                      - disk:
                          bus: virtio
                        name: cloudinitdisk
                    interfaces:
                      - name: default
                        masquerade: {}
                    networkInterfaceMultiqueue: true
                    rng: {}
                  machine:
                    type: pc-q35-rhel8.4.0
                  resources:
                    requests:
                      memory: 2Gi
                evictionStrategy: LiveMigrate
                hostname: "{{ vm_name[1] }}"
                networks:
                  - name: default
                    pod: {}
                terminationGracePeriodSeconds: 180
                volumes:
                  - dataVolume:
                      name: "{{ vm_name[1] }}"
                    name: "{{ vm_name[1] }}"
                  - cloudInitNoCloud:
                      userData: |-
                        #cloud-config
                        user: developer
                        password: developer
                        chpasswd: { expire: False }
                        runcmd:
                          - sudo sed -i "s/! Welcome to Red Hat Training/, from $HOSTNAME/g" /var/www/html/index.html
                          - sudo restorecon -Rv /var/www/html/
                    name: cloudinitdisk
        wait: yes
        wait_condition:
          type: Ready
          status: "True"
        wait_sleep: 60
        wait_timeout: 1800
