---
- name: Cleanup the utility system after lab
  hosts: utility
  remote_user: lab
  gather_facts: false
  become: true

  tasks:
    - name: Ensure the disk image does not exist
      file:
        path: /var/www/html/openshift4/images/storage-review.qcow2
        state: absent

    - name: Ensure an NFS share does not exist
      file:
        path: /exports-ocp4/storage-review
        state: absent
...
