apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    flavor.template.kubevirt.io/small: "true"
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: 7aaf118c-f174-3eba-9ec5-680cd791a020
    kubevirt.io/domain: vm1
    kubevirt.io/nodeName: worker02
    kubevirt.io/size: small
    os.template.kubevirt.io/rhel8.4: "true"
    vm.kubevirt.io/name: vm1
    workload.template.kubevirt.io/server: "true"
  name: vm1
spec:
  ports:
  - port: 22
    protocol: TCP
    targetPort: 22
    name: ssh
  - port: 3306
    protocol: TCP
    targetPort: 3306
    name: mysql
  selector:
    kubevirt.io/domain: vm1
  type: LoadBalancer
status:
  loadBalancer: {}
